---
abstract: 'Easily SSH to many servers'
author:
  - 'Dominic Humphries <dominic@oneandoneis2.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.037
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Goto2
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  IO::Interactive: 0
  MooseX::App::Simple: 0
  Net::Amazon::EC2: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/oneandoneis2/App-Goto2/issues
  homepage: https://github.com/oneandoneis2/App-Goto2
  repository: https://github.com/oneandoneis2/App-Goto2.git
version: 0.03
x_contributors:
  - 'Dominic Humphries <dominich@broadbean.com>'
